# Generated by Django 3.2.7 on 2021-09-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('top_light_color', models.CharField(max_length=200)),
                ('middle_light_color', models.CharField(max_length=200)),
                ('bottom_light_color', models.CharField(max_length=200)),
                ('top_light_duration', models.IntegerField(default=3)),
                ('middle_light_duration', models.IntegerField(default=3)),
                ('bottom_light_duration', models.IntegerField(default=3)),
                ('container_color', models.CharField(max_length=200)),
            ],
        ),
    ]
